version: "3.4"
services:
 nttdata-case:
   image: node:alpine
   container_name: nttdata-case
   entrypoint: /bin/sh
   ports:
     - 8000:8000
   working_dir: /srv/app
   environment:
     - MODE=development
     - VITE_KEY=1Ot7wiOJwD97UtIbVc9qd5zRyOlvxYpdQzwdZa-TfWs
   volumes:
     - type: bind
       source: ./
       target: /srv/app
   tty: true